src/apps/contacts/urls.py
from django.urls import path, include

from .views import contact_detail_view, contact_create_view, contact_list_view, contact_edit_view, contact_delete_view, contact_photo_view, contact_search_view
from .api import api_search

urlpatterns = [
    path('api/search/', api_search , name='api_search'),
    path('search/', contact_search_view , name='search'),
    path('<int:contact_id>/', contact_detail_view , name='contact_detail'),
    path('create/', contact_create_view , name='contact_create'),
    path('<int:contact_id>/edit/', contact_edit_view , name='contact_edit'),
    path('<int:contact_id>/delete/', contact_delete_view , name='contact_delete'),
    path('list/', contact_list_view , name='contact_list'),
    path('<int:contact_id>/image/', contact_photo_view, name = 'contact_image_upload'),
]

src/src/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views
from django.conf import settings
from django.conf.urls.static import static

from apps.core.views import homepage_view, signup_view
# from apps.contacts.views import contact_detail_view, contact_create_view
# from apps.userprofile.views import dashboard_view

urlpatterns = [
    path('', homepage_view, name='homepage'),
    path('admin/', admin.site.urls),
    path('signup/', signup_view, name='signup'),
    path('login/', views.LoginView.as_view(template_name = 'core/login.html') , name='login'),
    path('logout/', views.LogoutView.as_view() , name='logout'),
    path('contact/', include('apps.contacts.urls')),
    path('dashboard/', include('apps.userprofile.urls')),

    path('api/', include('apps.api.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/apps/contacts/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Contact(models.Model):
    first_name = models.CharField(max_length=255)
    last_name = models.CharField(max_length=255)
    job_title = models.CharField(max_length=255)
    company_name = models.CharField(max_length=255)
    email = models.CharField(max_length=255)
    phone = models.CharField(max_length=255)
    address = models.TextField(blank=True, null=True)
    photo = models.ImageField(upload_to='images/', blank=True, null=True) 
    created_by = models.ForeignKey(User, related_name='contacts', on_delete=models.SET_NULL, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    private = models.BooleanField(default=False)

    def __str__(self):
        return self.first_name + " " + self.last_name

src/apps/contacts/forms.py
from django import forms
from .models import Contact

class CreateContactForm(forms.ModelForm):
    class Meta:
        model = Contact
        fields = ['first_name', 'last_name', 'email', 'phone', 'address', 'job_title', 'company_name']

class ImageForm(forms.ModelForm): 
    class Meta: 
        model = Contact 
        fields = ['photo'] 

src/apps/contacts/views.py
from django.http import HttpResponse
from django.core.paginator import Paginator
from django.shortcuts import render, redirect, get_list_or_404, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.core.exceptions import ObjectDoesNotExist

from .forms import CreateContactForm, ImageForm
from .models import Contact

# Create your views here.
@login_required
def contact_detail_view(request, contact_id):
    contact = Contact.objects.get(pk=contact_id)
    context={
        "contact": contact
    }
    return render(request, 'contacts/contact_detail.html', context)

@login_required
def contact_create_view(request):
    if request.method == 'POST':
        form = CreateContactForm(request.POST)

        if form.is_valid():
            contact = form.save(commit=False)
            contact.created_by = request.user
            contact.save()
            # redirect to list all next
            return redirect('contact_list')
    else:
        form = CreateContactForm()

    context = {
        "form": form
    }
    return render(request, 'contacts/contact_create.html', context)

@login_required
def contact_edit_view(request, contact_id):
    contact = get_object_or_404(Contact, pk=contact_id, created_by=request.user)
    if request.method == 'POST':
        form = CreateContactForm(request.POST, instance=contact)

        if form.is_valid():
            contact = form.save(commit=False)
            contact.created_by = request.user
            contact.save()
            # redirect to list all next
            return redirect('contact_list')
    else:
        form = CreateContactForm(instance=contact)

    context = {
        "form": form,
        "contact": contact
    }
    return render(request, 'contacts/contact_edit.html', context)

@login_required
def contact_list_view(request):
    # contact_list = get_list_or_404(Contact.objects.all().order_by('-updated_at'), created_by=request.user)
    try:
        contact_list = Contact.objects.filter(created_by=request.user).order_by('first_name')
    except ObjectDoesNotExist:
        contact_list = []
    paginator = Paginator(contact_list, 5) # Show 25 contacts per page.

    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    return render(request, 'list.html', {'page_obj': page_obj})

@login_required
def contact_delete_view(request, contact_id):
    obj = get_object_or_404(Contact, id=contact_id)
    if request.method == "POST":
        obj.delete()
        return redirect('contact_list')
        
    context = {
        "object":obj
    }
    return render(request, "contacts/contact_delete.html", context)

@login_required
def contact_photo_view(request, contact_id):
    contact = get_object_or_404(Contact, pk=contact_id, created_by=request.user)
    if request.method == 'POST':
        form = ImageForm(request.POST, request.FILES, instance=contact)

        if form.is_valid():
            form.save()
            return redirect('../')
    else:
        form = ImageForm(instance=contact)
    return render(request, 'contacts/contact_photo.html', {"form": form, "contact": contact})

def contact_search_view(request):
    return render(request, 'contacts/contact_search.html')

src/apps/contacts/templates/contacts/contact_create.html
  
{% extends 'core/base.html' %}

{% block content %}
<div id="create-contact-app">
    <h1 class="title">Create Contact</h1>

    <form v-on:submit="validateForm" method="POST" action="." enctype="multipart/form-data">{% csrf_token %}
        {% if form.errors %}
            {% for error in form.errors %}
                <div class="notification is-danger">
                    {{ error }}
                </div>
            {% endfor %}
        {% endif %}

        <div class="notification is-danger" v-if="errors.length">
            <p v-for="error in errors">
                [[ error ]]
            </p>
        </div>

        <div class="field">
            <label>First Name</label>
            <div class="control">
                <input class="input" type="text" name="first_name" id="id_first_name" v-model="first_name">
            </div>
        </div>
        <div class="field">
            <label>Last Name</label>
            <div class="control">
                <input class="input" type="text" name="last_name" id="id_last_name" v-model="last_name">
            </div>
        </div>
        <div class="field">
            <label>Email</label>
            <div class="control">
                <input class="input" type="email" name="email" id="id_email" v-model="email">
            </div>
        </div>
        <div class="field">
            <label>Phone</label>
            <div class="control">
                <input class="input" type="phone" name="phone" id="id_phone" v-model="phone">
            </div>
        </div>
        <div class="field">
            <label>Job Title</label>
            <div class="control">
                <input class="input" type="text" name="job_title" id="id_job_title" v-model="job_title">
            </div>
        </div>
        <div class="field">
            <label>Company</label>
            <div class="control">
                <input class="input" type="text" name="company_name" id="id_company_name" v-model="company_name">
            </div>
        </div>
        <div class="field">
            <label>Address</label>
            <div class="control">
                <input class="textarea" type="textarea" name="address" id="id_address" v-model="address">
            </div>
        </div>
        <!-- {{form.as_p}} -->
        <div class="field">
            <div class="control">
                <button class="button is-success">Create</button>
            </div>
        </div>
    </form>
</div>
{% endblock %}

{% block scripts %}
<script>
    const CreateContactApp = {
        data() {
            return {
                first_name: '',
                last_name: '',
                email: '',
                phone: '',
                job_title: '',
                company_name: '',
                address: '',
                errors: []
            }
        },
        delimiters: ['[[', ']]'],
        methods: {
            validateForm(e) {
                this.errors = []

                if (this.first_name === '') {
                    this.errors.push('First Name is Missing!')
                }

                if (this.last_name === '') {
                    this.errors.push('Last Name is Missing!')
                }

                if (this.email === '') {
                    this.errors.push('Email is Missing!')
                }

                if (this.phone === '') {
                    this.errors.push('Phone is Missing!')
                }

                if (this.job_title === '') {
                    this.errors.push('Job Title is Missing!')
                }

                if (this.company_name === '') {
                    this.errors.push('Company is Missing!')
                }

                if (this.address === '') {
                    this.errors.push('Address is Missing!')
                }

                if (this.errors.length) {
                    e.preventDefault()

                    return false
                } else {
                    return true
                }
            }
        }
    }

    Vue.createApp(CreateContactApp).mount('#create-contact-app');
</script>
{% endblock %}

src/apps/contacts/templates/contacts/contact_delete.html
  
{% extends 'core/base.html' %}

{% block content %}
    <form action="." method="POST">{% csrf_token %}
        <h1>Do you want to delete contact "{{object.first_name}} {{object.last_name}}"?</h1>
        <p><input type="submit" value="Yes"/><a href="../">Cancel</a></p>
    </form>
{% endblock %}

src/apps/contacts/templates/contacts/contact_detail.html
  
{% extends 'core/base.html' %}

{% block content %}
    <h1 class="title">{{ contact.first_name }} {{ contact.last_name }}</h1>
    <!-- <div class="navbar-menu">
        <div class="navbar-end"> -->
            <a href="{% url 'contact_image_upload' contact.id %}" class="button is-warning mb-4">Photo</a>
            <a href="{% url 'contact_edit' contact.id %}" class="button is-success mb-4">Edit</a>
            <a href="{% url 'contact_delete' contact.id %}" class="button is-danger mb-4">Delete</a>
        <!-- </div>
    </div> -->
    {% if contact.photo %}
    <div class="col-md-4"> 
        <img src="{{ contact.photo.url }}" class="img-responsive" style="width: 12%; float: left; margin-right: 10px;" /> 
    </div>
    {% else %}
    <div class="col-md-4"> 
        <img src="../../../../media/noimage.jpg" class="img-responsive" style="width: 12%; float: left; margin-right: 10px;">
    </div>
    {% endif %}
    
    {% if contact.job_title %}<b>Position: </b>{{ contact.job_title}}<br>{% endif %}
    {% if contact.company_name %}<b>Company: </b>{{ contact.company_name}}<br>{% endif %}
    {% if contact.email %}<b>Email: </b>{{ contact.email}}<br>{% endif %}
    {% if contact.phone %}<b>Phone: </b>{{ contact.phone}}<br>{% endif %}
    {% if contact.address %}<b>Address: </b>{{ contact.address}}<br>{% endif %}
    <hr>

    {% if contact.created_by %}<b>Created By: </b>{{ contact.created_by}}<br>{% endif %}
    {% if contact.created_at %}<b>Created At: </b>{{ contact.created_at}}<br>{% endif %}
    {% if contact.updated_at %}<b>Updated At: </b>{{ contact.updated_at}}<br>{% endif %}
{% endblock %}

src/apps/contacts/templates/contacts/contact_edit.html
  
{% extends 'core/base.html' %}

{% block content %}
<div id="edit-contact-app">
    <h1 class="title">Create Contact</h1>

    <form v-on:submit="validateForm" method="POST" action="." enctype="multipart/form-data">{% csrf_token %}
        {% if form.errors %}
            {% for error in form.errors %}
                <div class="notification is-danger">
                    {{ error }}
                </div>
            {% endfor %}
        {% endif %}

        <div class="notification is-danger" v-if="errors.length">
            <p v-for="error in errors">
                [[ error ]]
            </p>
        </div>

        <div class="field">
            <label>First Name</label>
            <div class="control">
                <input class="input" type="text" name="first_name" id="id_first_name" v-model="first_name" value="{% if contact.first_name %}{{contact.first_name}}{% endif %}">
            </div>
        </div>
        <div class="field">
            <label>Last Name</label>
            <div class="control">
                <input class="input" type="text" name="last_name" id="id_last_name" v-model="last_name" value="{% if contact.last_name %}{{contact.last_name}}{% endif %}">
            </div>
        </div>
        <div class="field">
            <label>Email</label>
            <div class="control">
                <input class="input" type="email" name="email" id="id_email" v-model="email" value="{% if contact.email %}{{contact.email}}{% endif %}">
            </div>
        </div>
        <div class="field">
            <label>Phone</label>
            <div class="control">
                <input class="input" type="phone" name="phone" id="id_phone" v-model="phone" value="{% if contact.phone %}{{contact.phone}}{% endif %}">
            </div>
        </div>
        <div class="field">
            <label>Job Title</label>
            <div class="control">
                <input class="input" type="text" name="job_title" id="id_job_title" v-model="job_title" value="{% if contact.job_title %}{{contact.job_title}}{% endif %}">
            </div>
        </div>
        <div class="field">
            <label>Company</label>
            <div class="control">
                <input class="input" type="text" name="company_name" id="id_company_name" v-model="company_name" value="{% if contact.company_name %}{{contact.company_name}}{% endif %}">
            </div>
        </div>
        <div class="field">
            <label>Address</label>
            <div class="control">
                <input class="textarea" type="textarea" name="address" id="id_address" v-model="address" value="{% if contact.first_name %}{{contact.address}}{% endif %}">
            </div>
        </div>
        <!-- {{form.as_p}} -->
        <div class="field">
            <div class="control">
                <button class="button is-success">Edit</button>
            </div>
        </div>
    </form>
</div>
{% endblock %}

{% block scripts %}
<script>
    const EditContactApp = {
        data() {
            return {
                first_name: '{{contact.first_name}}',
                last_name: '{{contact.last_name}}',
                email: '{{contact.email}}',
                phone: '{{contact.phone}}',
                job_title: '{{contact.job_title}}',
                company_name: '{{contact.company_name}}',
                address: '{{contact.address}}',
                errors: []
            }
        },
        delimiters: ['[[', ']]'],
        methods: {
            validateForm(e) {
                this.errors = []

                if (this.first_name === '') {
                    this.errors.push('First Name is Missing!')
                }

                if (this.last_name === '') {
                    this.errors.push('Last Name is Missing!')
                }

                if (this.email === '') {
                    this.errors.push('Email is Missing!')
                }

                if (this.phone === '') {
                    this.errors.push('Phone is Missing!')
                }

                if (this.job_title === '') {
                    this.errors.push('Job Title is Missing!')
                }

                if (this.company_name === '') {
                    this.errors.push('Company is Missing!')
                }

                if (this.address === '') {
                    this.errors.push('Address is Missing!')
                }

                if (this.errors.length) {
                    e.preventDefault()

                    return false
                } else {
                    return true
                }
            }
        }
    }

    Vue.createApp(EditContactApp).mount('#edit-contact-app');
</script>
{% endblock %}

src/apps/contacts/templates/contacts/contact_photo.html
      
{% extends 'core/base.html' %}

{% block content %}
    <h1 class="title">Update Contact Photo: {{contact.first_name}} {{contact.last_name}}</h1>
    <form method = "POST" enctype="multipart/form-data"> 
        {% csrf_token %} 
        {{ form.as_p }} 
        <button type="submit">Upload</button> 
    </form> 
{% endblock %}

src/apps/contacts/templates/contacts/contact_search.html
{% extends 'core/base.html' %}

{% block content %}
    <div id="search-app">
        <h1 class="title">Search</h1>

        <form @submit.prevent="performSearch()">
            <div class="columns">
                <div class="column is-4">
                    <div class="field">
                        <label>Query</label>

                        <div class="control">
                            <input type="text" name="query" class="input" v-model="query">
                        </div>
                    </div> 

                    <div class="field">
                        <div class="control">
                            <button class="button is-success">Search</button>
                        </div>
                    </div>
                </div>
            </div>
        </form>

        <div v-if="contacts.length">
            <hr>

            <div
                v-for="contact in contacts"
                :key="contact.id"
                class="notification mt-2"
            >
                <h3 class="is-size-4">[[ contact.first_name ]] [[ contact.last_name ]]</h3>
                <p>[[ contact.email ]]</p>
                <p>[[ contact.phone ]]</p>
                <p>[[ contact.job_title ]]</p>
                <p>[[ contact.company_name ]]</p>
                <p>[[ contact.address ]]</p>

                <a :href="contact.url">View details</a>
            </div>
        </div>
    </div>
{% endblock %}

{% block scripts %}
<script>
    const SearchApp = {
        data() {
            return {
                query: '',
                contacts: []
            }
        },
        delimiters: ['[[', ']]'],
        methods: {
            performSearch() {
                var data = {
                    'query': this.query
                }

                fetch('/contact/api/search/', {
                    method: 'POST',
                    headers: {
                        'Content-Type': 'application/json',
                        'X-CSRFToken': '{{ csrf_token }}'
                    },
                    body: JSON.stringify(data)
                })
                .then((response) => {
                    return response.json()
                })
                .then((result) => {
                    console.log(result.contacts)
                    this.contacts = result.contacts
                })
                .catch((error) => {
                    console.log('Error', error)
                })
            }
        }
    }

    Vue.createApp(SearchApp).mount('#search-app')
</script>
{% endblock %}